// Re-export all Supabase storage functions for backward compatibility
export {
  generateInvoiceNumber,
  getBakeries,
  addBakery,
  updateBakery,
  deleteBakery,
  getItems,
  addItem,
  updateItem,
  deleteItem,
  getSales,
  addSale,
  updateSale,
  getAdmin,
  saveAdmin,
  getTodaySales,
  getTodayStats,
  getTopItemsToday,
  getRecentlyUsedBakeries,
} from "./supabase-storage";
